import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Script from "next/script";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LoginBanner from "@/components/LoginBanner";
import AuthProvider from "@/components/AuthProvider";
import ConditionalLayout from "@/components/ConditionalLayout";
import ConnectAIButton from "@/components/connect/ConnectAIButton";

const netflixSans = localFont({
  src: [
    { path: "./fonts/NetflixSansThin.ttf", weight: "100" },
    { path: "./fonts/NetflixSansLight.ttf", weight: "300" },
    { path: "./fonts/NetflixSansRegular.ttf", weight: "400" },
    { path: "./fonts/NetflixSansMedium.ttf", weight: "500" },
    { path: "./fonts/NetflixSansBold.ttf", weight: "700" },
    { path: "./fonts/NetflixSansBlack.ttf", weight: "900" },
  ],
  variable: "--font-netflix",
});

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by Netflix",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={netflixSans.variable}>
        <AuthProvider>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
          <ConnectAIButton />
        </AuthProvider>
        <Script 
          src="https://developers.kakao.com/sdk/js/kakao.js" 
          strategy="afterInteractive" 
        />
        <Script 
          src="https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.0.js" 
          strategy="afterInteractive" 
        />
      </body>
    </html>
  );
}