import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import "./globals.scss";

import AuthProvider from "@/components/AuthProvider";
import ConditionalLayout from "@/components/ConditionalLayout";
import ScrollToTop from "@/components/common/ScrollToTop";
import ConnectAIWrapper from "@/components/connect/ConnectAIWrapper";

const netflixSans = localFont({
  src: [
    { path: "./fonts/NetflixSansThin.ttf", weight: "100" },
    { path: "./fonts/NetflixSansLight.ttf", weight: "300" },
    { path: "./fonts/NetflixSansRegular.ttf", weight: "400" },
    { path: "./fonts/NetflixSansMedium.ttf", weight: "500" },
    { path: "./fonts/NetflixSansBold.ttf", weight: "700" },
    { path: "./fonts/NetflixSansBlack.ttf", weight: "900" },
  ],
  variable: "--font-netflix",
});

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by Netflix",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  colorScheme: "dark",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={netflixSans.variable}>
        {/* ... */}
        <AuthProvider>
          <Suspense fallback={null}>
            <ScrollToTop />
          </Suspense>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
          {/* 래퍼를 통해 안전하게 렌더링 */}
          <ConnectAIWrapper />
        </AuthProvider>
      </body>
    </html>
  );
}
