import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LoginBanner from "@/components/LoginBanner";

const netflixSans = localFont({
  src: [
    { path: "./fonts/NetflixSansThin.ttf", weight: "100" },
    { path: "./fonts/NetflixSansLight.ttf", weight: "300" },
    { path: "./fonts/NetflixSansRegular.ttf", weight: "400" },
    { path: "./fonts/NetflixSansMedium.ttf", weight: "500" },
    { path: "./fonts/NetflixSansBold.ttf", weight: "700" },
    { path: "./fonts/NetflixSansBlack.ttf", weight: "900" },
  ],
  variable: "--font-netflix",
});

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by Netflix",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={netflixSans.variable}>
        <Header />
        <main>{children}</main>
        <Footer />
        {/* 비로그인 사용자에게 표시되는 하단 고정 배너 */}
        <LoginBanner />
      </body>
    </html>
  );
}